apiVersion: v1
kind: Service
metadata:
  name: digicloset-python-metrics
  labels:
    app: digicloset-python
spec:
  selector:
    app: digicloset-python
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: digicloset-python-metrics
subsets:
  - addresses:
      - ip: <EXTERNAL_PROMETHEUS_IP>
    ports:
      - port: 9101