# prometheus_remote_write.yaml
# Configure your application metrics to be scraped and sent to an external Prometheus / Grafana Cloud endpoint.

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'digicloset-node'
    static_configs:
      - targets: ['digicloset-node-metrics:9100']
  - job_name: 'digicloset-python'
    static_configs:
      - targets: ['digicloset-python-metrics:9101']

remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: <GRAFANA_CLOUD_USER_ID>
      password: <GRAFANA_CLOUD_API_KEY>